name = "ZenithSMP"
author = "mwxkhmy (base: quickqwek)"
version = "v2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42e6060a0b1c6322527182c2fb03c31e496acff7bfaf2722d89f052e9b7c8e11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
