name = "ZenithSMP"
author = "mwxkhmy (base: quickqwek)"
version = "v2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "694011a8d297d794edefa0385f7a97e260701c288ad4a84cd7223c66fb71d3fa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
