name = "ZenithSMP"
author = "mwxkhmy (base: quickqwek)"
version = "v2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "413647b68396649e8f38ea89b6e90b4bc0a5d92c73d18c012f49ba0f7fc0b1a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
